package com.github.daniilbug.auth.exceptions

class UserAlreadyExistsException: Exception("User with that email already exists")